// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as cloud from "./namespaces/cloud";
import * as common from "./namespaces/common";
import * as dictionary from "./namespaces/dictionary";
import * as notify from "./namespaces/notify";
import * as page_url from "./namespaces/page_url";
import * as permission from "./namespaces/permission";
import * as sheet from "./namespaces/sheet";
import * as tcc from "./namespaces/tcc";
import * as upload from "./namespaces/upload";

export {
  cloud,
  common,
  dictionary,
  notify,
  page_url,
  permission,
  sheet,
  tcc,
  upload,
};

export type Int64 = string | number;

export default class BesFeWebCoreService<T> {
  private request: any = () => {
    throw new Error("BesFeWebCoreService.request is undefined");
  };
  private baseURL: string | ((path: string) => string) = "";

  constructor(options?: {
    baseURL?: string | ((path: string) => string);
    request?<R>(
      params: {
        url: string;
        method: "GET" | "DELETE" | "POST" | "PUT" | "PATCH";
        data?: any;
        params?: any;
        headers?: any;
      },
      options?: T
    ): Promise<R>;
  }) {
    this.request = options?.request || this.request;
    this.baseURL = options?.baseURL || "";
  }

  private genBaseURL(path: string) {
    return typeof this.baseURL === "string"
      ? this.baseURL + path
      : this.baseURL(path);
  }

  /**
   * GET /api/core/common/CheckEnvHeader
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=2682619)
   *
   * 用于提醒用户是否携带了 x-tt-env 等特殊 header
   */
  CheckEnvHeader(
    req?: common.CheckEnvHeaderReq,
    options?: T
  ): Promise<common.CheckEnvHeaderResp> {
    const url = this.genBaseURL("/api/core/common/CheckEnvHeader");
    const method = "GET";
    return this.request({ url, method }, options);
  }

  /**
   * GET /api/core/notify/msg/list
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=2756168)
   */
  NotifyMsgList(
    req?: notify.NotifyMsgListReq,
    options?: T
  ): Promise<notify.NotifyMsgListResp> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/notify/msg/list");
    const method = "GET";
    const params = {
      msg_business_type: _req["msg_business_type"],
      page_size: _req["page_size"],
      page_num: _req["page_num"],
    };
    return this.request({ url, method, params }, options);
  }

  /**
   * GET /api/core/notify/msg/detail
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=2756311)
   */
  GetNotifyMsgById(
    req?: notify.GetNotifyMsgByIdReq,
    options?: T
  ): Promise<notify.GetNotifyMsgByIdResp> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/notify/msg/detail");
    const method = "GET";
    const params = { content_id: _req["content_id"], msg_id: _req["msg_id"] };
    return this.request({ url, method, params }, options);
  }

  /**
   * POST /api/core/notify/msg/update
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=2756425)
   */
  UpdateNotifyMsgStatus(
    req: notify.UpdateNotifyMsgStatusReq,
    options?: T
  ): Promise<notify.UpdateNotifyMsgStatusResp> {
    const _req = req;
    const url = this.genBaseURL("/api/core/notify/msg/update");
    const method = "POST";
    const data = { msg_id: _req["msg_id"], status: _req["status"] };
    return this.request({ url, method, data }, options);
  }

  /**
   * GET /api/core/notify/msg/get_unread_num
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=2786750)
   */
  GetUnReadNum(
    req?: notify.GetUnReadNumReq,
    options?: T
  ): Promise<notify.GetUnReadNumResp> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/notify/msg/get_unread_num");
    const method = "GET";
    const params = { msg_business_type: _req["msg_business_type"] };
    return this.request({ url, method, params }, options);
  }

  /**
   * GET /api/core/cloud/psm/check
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=2900253)
   */
  CheckPSM(req?: cloud.CheckPSMReq, options?: T): Promise<cloud.CheckPSMResp> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/cloud/psm/check");
    const method = "GET";
    const params = { psm: _req["psm"] };
    return this.request({ url, method, params }, options);
  }

  /**
   * GET /api/core/cloud/psm/owners
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=2900254)
   */
  GetOwnersByPsm(
    req?: cloud.GetOwnersByPsmReq,
    options?: T
  ): Promise<cloud.GetOwnersByPsmResp> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/cloud/psm/owners");
    const method = "GET";
    const params = { psm: _req["psm"] };
    return this.request({ url, method, params }, options);
  }

  /**
   * POST /api/core/tcc/modify
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=2964949)
   *
   * 编辑&发布接口
   */
  ModifyTCC(req?: tcc.ModifyRequest, options?: T): Promise<tcc.ModifyTCCResp> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/tcc/modify");
    const method = "POST";
    const data = {
      service_name: _req["service_name"],
      region: _req["region"],
      confspace: _req["confspace"],
      key: _req["key"],
      value: _req["value"],
      from_version: _req["from_version"],
      env: _req["env"],
      note: _req["note"],
      app_name: _req["app_name"],
      operator: _req["operator"],
      token: _req["token"],
      service_id: _req["service_id"],
      config_id: _req["config_id"],
    };
    return this.request({ url, method, data }, options);
  }

  /**
   * GET /api/core/queue/permission
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=2984427)
   */
  getQueuePermission(
    req?: permission.QPermissionReq,
    options?: T
  ): Promise<permission.GetQPermissionRes> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/queue/permission");
    const method = "GET";
    const params = { category: _req["category"], points: _req["points"] };
    return this.request({ url, method, params }, options);
  }

  /**
   * GET /api/core/queue/page_url
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3043899)
   */
  getPageUrl(
    req?: page_url.QPageReq,
    options?: T
  ): Promise<page_url.GetPageUrlRes> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/queue/page_url");
    const method = "GET";
    const params = {
      clickAuditFrom: _req["clickAuditFrom"],
      redirect: _req["redirect"],
      objectId: _req["objectId"],
      auditLogId: _req["auditLogId"],
      taskId: _req["taskId"],
      objectCategory: _req["objectCategory"],
      objectType: _req["objectType"],
      queueKey: _req["queueKey"],
      staffId: _req["staffId"],
      retrieveUnAudit: _req["retrieveUnAudit"],
    };
    return this.request({ url, method, params }, options);
  }

  /**
   * GET /api/core/dictionary/find_word
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3345131)
   *
   * 查询词
   */
  FindWord(
    req?: dictionary.FindWordRequest,
    options?: T
  ): Promise<dictionary.FindWordResponse> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/dictionary/find_word");
    const method = "GET";
    const params = {
      appid: _req["appid"],
      word: _req["word"],
      word_id: _req["word_id"],
    };
    return this.request({ url, method, params }, options);
  }

  /**
   * POST /api/core/dictionary/build_words_cache
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3345132)
   *
   * 构建缓存
   */
  BuildWordsCache(
    req?: dictionary.BuildWordsCacheRequest,
    options?: T
  ): Promise<dictionary.BuildWordsCacheResponse> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/dictionary/build_words_cache");
    const method = "POST";
    const data = { appid: _req["appid"], async: _req["async"] };
    return this.request({ url, method, data }, options);
  }

  /**
   * POST /api/core/dictionary/search_matched_words
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3345133)
   *
   * 匹配词
   */
  SearchMatchedWords(
    req?: dictionary.SearchMatchedWordsRequest,
    options?: T
  ): Promise<dictionary.SearchMatchedWordsResponse> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/dictionary/search_matched_words");
    const method = "POST";
    const data = {
      appid: _req["appid"],
      url: _req["url"],
      content: _req["content"],
    };
    return this.request({ url, method, data }, options);
  }

  /**
   * POST /api/core/dictionary/del_word
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3345134)
   *
   * 下线词
   */
  DelWord(
    req?: dictionary.DelWordRequest,
    options?: T
  ): Promise<dictionary.DelWordResponse> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/dictionary/del_word");
    const method = "POST";
    const data = {
      word_id: _req["word_id"],
      del_staff_id: _req["del_staff_id"],
    };
    return this.request({ url, method, data }, options);
  }

  /**
   * GET /api/core/dictionary/get_words_total
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3345135)
   *
   * 获取所有在线词total
   */
  GetWordsTotal(
    req?: dictionary.GetWordsTotalRequest,
    options?: T
  ): Promise<dictionary.GetWordsTotalResponse> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/dictionary/get_words_total");
    const method = "GET";
    const params = { appid: _req["appid"], from_cache: _req["from_cache"] };
    return this.request({ url, method, params }, options);
  }

  /**
   * GET /api/core/dictionary/app_list
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3345136)
   */
  ListApp(
    req?: dictionary.ListAppRequest,
    options?: T
  ): Promise<dictionary.ListAppResponse> {
    const url = this.genBaseURL("/api/core/dictionary/app_list");
    const method = "GET";
    return this.request({ url, method }, options);
  }

  /**
   * POST /api/core/dictionary/create_word
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3345137)
   *
   * 创建词
   */
  CreateWord(
    req?: dictionary.CreateWordRequest,
    options?: T
  ): Promise<dictionary.CreateWordResponse> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/dictionary/create_word");
    const method = "POST";
    const data = {
      appid: _req["appid"],
      word: _req["word"],
      en_word: _req["en_word"],
      content: _req["content"],
      create_staff_id: _req["create_staff_id"],
      owners: _req["owners"],
      image_links: _req["image_links"],
      lark_doc_links: _req["lark_doc_links"],
      web_links: _req["web_links"],
      lark_chat_ids: _req["lark_chat_ids"],
    };
    return this.request({ url, method, data }, options);
  }

  /**
   * POST /api/core/dictionary/update_word
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3345138)
   *
   * 更新词
   */
  UpdateWord(
    req?: dictionary.UpdateWordRequest,
    options?: T
  ): Promise<dictionary.UpdateWordResponse> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/dictionary/update_word");
    const method = "POST";
    const data = {
      word_id: _req["word_id"],
      word: _req["word"],
      en_word: _req["en_word"],
      content: _req["content"],
      update_staff_id: _req["update_staff_id"],
      lark_doc_links: _req["lark_doc_links"],
      web_links: _req["web_links"],
      lark_chat_ids: _req["lark_chat_ids"],
    };
    return this.request({ url, method, data }, options);
  }

  /**
   * POST /api/core/sheet/export_v2
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3364456)
   */
  ExportSheetV2(
    req: sheet.ExportSheetV2Req,
    options?: T
  ): Promise<sheet.ExportSheetResponse> {
    const _req = req;
    const url = this.genBaseURL("/api/core/sheet/export_v2");
    const method = "POST";
    const data = {
      lark: _req["lark"],
      sheetName: _req["sheetName"],
      records: _req["records"],
      rawSheetData: _req["rawSheetData"],
      options: _req["options"],
    };
    return this.request({ url, method, data }, options);
  }

  /**
   * POST /api/core/sheet/export
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3364457)
   */
  ExportSheet(
    req: sheet.ExportSheetReq,
    options?: T
  ): Promise<sheet.ExportSheetResponse> {
    const _req = req;
    const url = this.genBaseURL("/api/core/sheet/export");
    const method = "POST";
    const data = {
      records: _req["records"],
      rawSheetData: _req["rawSheetData"],
      defaultHeader: _req["defaultHeader"],
      sheetName: _req["sheetName"],
      lark: _req["lark"],
      sortCols: _req["sortCols"],
      folder: _req["folder"],
      fileName: _req["fileName"],
      typeMap: _req["typeMap"],
    };
    return this.request({ url, method, data }, options);
  }

  /**
   * POST /api/core/common/CheckWaterMark
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3366844)
   */
  CheckWaterMark(
    req: common.CheckWaterMarkReq,
    options?: T
  ): Promise<common.CheckWaterMarkResp> {
    const _req = req;
    const url = this.genBaseURL("/api/core/common/CheckWaterMark");
    const method = "POST";
    const data = {
      appId: _req["appId"],
      appSecret: _req["appSecret"],
      imageUrl: _req["imageUrl"],
    };
    return this.request({ url, method, data }, options);
  }

  /**
   * POST /api/core/upload/file
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3371040)
   */
  FileUpload(
    req?: upload.FileImageUploadRequest,
    options?: T
  ): Promise<upload.FileUploadResp> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/upload/file");
    const method = "POST";
    const data = { bizType: _req["bizType"] };
    return this.request({ url, method, data }, options);
  }

  /**
   * GET /api/core/upload/admin/token
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3371041)
   */
  AdminToken(
    req?: upload.EmptyRequest,
    options?: T
  ): Promise<upload.TokenResp> {
    const url = this.genBaseURL("/api/core/upload/admin/token");
    const method = "GET";
    return this.request({ url, method }, options);
  }

  /**
   * GET /api/core/upload/video/token
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3371042)
   */
  VideoToken(
    req?: upload.VideoTokenRequest,
    options?: T
  ): Promise<upload.TokenResp> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/upload/video/token");
    const method = "GET";
    const params = { space: _req["space"] };
    return this.request({ url, method, params }, options);
  }

  /**
   * POST /api/core/upload/image
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3371043)
   */
  ImageUpload(
    req?: upload.ImageUploadRequest,
    options?: T
  ): Promise<upload.ImageUploadResp> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/upload/image");
    const method = "POST";
    const data = {
      accessType: _req["accessType"],
      fileKey: _req["fileKey"],
      bizType: _req["bizType"],
      fileData: _req["fileData"],
    };
    return this.request({ url, method, data }, options);
  }

  /**
   * POST /api/core/upload/token
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3371044)
   */
  Token(req?: upload.EmptyRequest, options?: T): Promise<upload.TokenResp> {
    const url = this.genBaseURL("/api/core/upload/token");
    const method = "POST";
    return this.request({ url, method }, options);
  }

  /**
   * POST /api/core/upload/callback
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3371045)
   */
  Callback(
    req: upload.CallbackRequest,
    options?: T
  ): Promise<upload.CallbackResp> {
    const _req = req;
    const url = this.genBaseURL("/api/core/upload/callback");
    const method = "POST";
    const data = {
      uris: _req["uris"],
      type: _req["type"],
      biz_type: _req["biz_type"],
      access_type: _req["access_type"],
    };
    return this.request({ url, method, data }, options);
  }

  /**
   * GET /api/core/upload/image/token
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3371046)
   */
  ImageToken(
    req?: upload.EmptyRequest,
    options?: T
  ): Promise<upload.TokenResp> {
    const url = this.genBaseURL("/api/core/upload/image/token");
    const method = "GET";
    return this.request({ url, method }, options);
  }

  /**
   * POST /api/core/upload/base64_image
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3371047)
   */
  Base64ImageUpload(
    req: upload.Base64ImageUploadRequest,
    options?: T
  ): Promise<upload.ImageUploadResp> {
    const _req = req;
    const url = this.genBaseURL("/api/core/upload/base64_image");
    const method = "POST";
    const data = {
      accessType: _req["accessType"],
      fileKey: _req["fileKey"],
      bizType: _req["bizType"],
      source: _req["source"],
    };
    return this.request({ url, method, data }, options);
  }

  /**
   * GET /api/core/dictionary/get_word_list
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3385225)
   *
   * 获取词列表
   */
  GetWordList(
    req?: dictionary.GetWordListRequest,
    options?: T
  ): Promise<dictionary.GetWordListResponse> {
    const _req = req || {};
    const url = this.genBaseURL("/api/core/dictionary/get_word_list");
    const method = "GET";
    const params = {
      appid: _req["appid"],
      page_num: _req["page_num"],
      page_size: _req["page_size"],
      word: _req["word"],
      owners: _req["owners"],
      tags: _req["tags"],
      word_status: _req["word_status"],
    };
    return this.request({ url, method, params }, options);
  }

  /**
   * POST /api/core/dictionary/batch_find_words
   *
   * [jump to BAM](https://cloud.bytedance.net/bam/rd/bes.fe.web_core/api_doc/show_doc?version=1.0.37&endpoint_id=3406830)
   *
   * 获取词列表
   */
  BatchFindWords(
    req: dictionary.BatchFindWordsRequest,
    options?: T
  ): Promise<dictionary.BatchFindWordsResponse> {
    const _req = req;
    const url = this.genBaseURL("/api/core/dictionary/batch_find_words");
    const method = "POST";
    const data = { words: _req["words"] };
    return this.request({ url, method, data }, options);
  }
}
/* eslint-enable */
