// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface CheckPSMData {
  valid?: boolean;
  msg?: string;
}

export interface CheckPSMReq {
  psm?: string;
}

export interface CheckPSMResp {
  code: number;
  message: string;
  data?: CheckPSMData;
}

export interface GetOwnersByPsmReq {
  psm?: string;
}

export interface GetOwnersByPsmResp {
  code: number;
  message: string;
  data?: PSMOwnersData;
}

export interface PSMOwnersData {
  owners?: Array<string>;
}
/* eslint-enable */
