// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface CheckEnvHeaderReq {}

export interface CheckEnvHeaderResp {
  code: number;
  message: string;
  /** 携带的特殊 header 列表 */
  data: Array<string>;
}

export interface CheckWaterMarkReq {
  appId: number;
  appSecret: string;
  imageUrl: string;
}

export interface CheckWaterMarkResp {
  code: number;
  message: string;
  /** 返回的水印信息 */
  result: string;
}
/* eslint-enable */
