// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum DictionaryBuildTaskStatus {
  RUNNING = 1,
  SUCCESS = 2,
  FAILED = 2,
}

export enum WordStatus {
  /** 删除 */
  DELETED = 0,
  /** 正常 */
  NORMAL = 1,
}

export interface AppInfo {
  /** 应用ID */
  appid?: number;
  /** 应用名称 */
  name?: string;
}

export interface BatchFindWordsRequest {
  /** 词列表 */
  words: Array<SimpleWord>;
}

export interface BatchFindWordsResponse {
  /** 词列表 */
  word_list: Array<WordData>;
}

export interface BuildWordsCacheRequest {
  /** 应用id, 默认 0 为公共词, 所有平台可用 */
  appid?: number;
  /** 是否异步, 默认false */
  async?: boolean;
}

export interface BuildWordsCacheResponse {
  /** 词数量 */
  total?: number;
  /** 构建缓存状态，running | success | failed */
  status?: DictionaryBuildTaskStatus;
  /** 错误信息 */
  err_msg?: string;
}

export interface CreateWordRequest {
  /** 应用ID, 默认 0 为公共词, 所有平台可用 */
  appid?: number;
  word?: string;
  /** 英文词 */
  en_word?: string;
  /** 文本内容 */
  content?: string;
  /** 创建人ID, 默认为0 表示系统创建 */
  create_staff_id?: number;
  /** 词负责人， 存储email */
  owners?: Array<string>;
  /** 图片展示链接 */
  image_links?: Array<string>;
  /** 相关飞书文档 */
  lark_doc_links?: Array<string>;
  /** 相关站点链接 */
  web_links?: Array<string>;
  /** 相关飞书群ID */
  lark_chat_ids?: Array<string>;
}

export interface CreateWordResponse {
  /** 词id */
  word_id?: number;
  /** 是否成功 */
  is_ok?: boolean;
  /** 错误信息 */
  err_msg?: string;
}

export interface DelWordRequest {
  word_id?: number;
  /** 修改人ID */
  del_staff_id?: number;
}

export interface DelWordResponse {
  is_ok?: boolean;
}

export interface FindWordRequest {
  /** 应用ID, 不填默认为0，填0则公共词 */
  appid?: number;
  word?: string;
  word_id?: number;
}

export interface FindWordResponse {
  word_data?: WordData;
}

export interface GetWordListRequest {
  /** 应用ID, 不填则搜索所有 */
  appid?: number;
  /** 页码 */
  page_num?: number;
  /** 页大小 */
  page_size?: number;
  /** 词名称 */
  word?: string;
  /** 词负责人， 存储email */
  owners?: Array<string>;
  /** 词标签 */
  tags?: Array<string>;
  /** 词状态，0-删除，1-正常 默认正常 */
  word_status?: WordStatus;
}

export interface GetWordListResponse {
  word_list?: Array<WordData>;
  /** 词数量 */
  total?: number;
}

export interface GetWordsTotalRequest {
  /** 应用ID, 不填则所有，填0则公共词 */
  appid?: number;
  /** 是否从redis缓存获取，默认false */
  from_cache?: boolean;
}

export interface GetWordsTotalResponse {
  /** 词数量 */
  total?: number;
}

export interface ListAppRequest {}

export interface ListAppResponse {
  app_list?: Array<AppInfo>;
}

export interface MatchedWordData {
  /** 词id */
  word_id?: number;
  /** appid */
  appid?: number;
}

export interface MatchedWords {
  word?: string;
  /** 词id列表，一词多意 */
  matches?: Array<MatchedWordData>;
}

export interface SearchMatchedWordsRequest {
  /** 应用id, 不传为所有词, 0 为公共词, 所有平台可用 */
  appid?: number;
  /** 网址 埋点用 */
  url?: string;
  content?: string;
}

export interface SearchMatchedWordsResponse {
  match_words?: Array<MatchedWords>;
}

export interface SimpleWord {
  /** 词名称 */
  word?: string;
  /** 应用ID */
  appid?: number;
}

export interface UpdateWordRequest {
  word_id?: number;
  /** 词名称 */
  word?: string;
  /** 英文词 */
  en_word?: string;
  /** 富文本内容 */
  content?: string;
  /** 修改人ID */
  update_staff_id?: number;
  /** 相关飞书文档 */
  lark_doc_links?: Array<string>;
  /** 相关站点链接 */
  web_links?: Array<string>;
  /** 相关飞书群ID */
  lark_chat_ids?: Array<string>;
}

export interface UpdateWordResponse {
  is_ok?: boolean;
}

export interface WordData {
  appid?: number;
  id?: number;
  /** 词名称 */
  word?: string;
  /** 英文词 */
  en_word?: string;
  /** 富文本内容 */
  content?: string;
  /** 别名 */
  alias_words?: Array<string>;
  /** 相关飞书文档 */
  lark_doc_links?: Array<string>;
  /** 相关站点链接 */
  web_links?: Array<string>;
  /** 相关飞书群ID */
  lark_chat_ids?: Array<string>;
  /** 词负责人， 存储email */
  owners?: Array<string>;
  /** 词标签 */
  tags?: Array<string>;
  /** 图片展示链接 */
  image_links?: Array<string>;
  /** 词状态，0-删除，1-正常 */
  word_status?: WordStatus;
  /** 创建时间 */
  created_at?: string;
  /** 修改时间 */
  updated_at?: string;
  /** 删除时间 */
  deleted_at?: string;
  /** 创建人ID */
  create_staff_id?: number;
  /** 修改人ID */
  update_staff_id?: number;
  /** 删除人ID */
  deleted_staff_id?: number;
}
/* eslint-enable */
