// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum NotifyMsgStatus {
  Init = 0,
  SendSuccess = 1,
  SendFailed = 2,
  Read = 5,
}

export interface GetNotifyMsgByIdReq {
  /** 内容ID */
  content_id?: number;
  /** 消息ID */
  msg_id?: number;
}

export interface GetNotifyMsgByIdResp {
  code: number;
  message: string;
  data?: NotifyMsg;
}

export interface GetUnReadNum {
  total: number;
}

export interface GetUnReadNumReq {
  /** 业务区分 */
  msg_business_type?: number;
}

export interface GetUnReadNumResp {
  code: number;
  message: string;
  data?: GetUnReadNum;
}

export interface NotifyContent {
  id?: number;
  title?: string;
  msg_theme?: string;
  status?: number;
  content?: string;
  btn_text?: string;
  btn_link?: string;
  create_time?: Int64;
  modify_time?: Int64;
}

export interface NotifyMsg {
  id: number;
  status: NotifyMsgStatus;
  status_name: string;
  create_time?: string;
  modify_time?: string;
  msg_business_type?: number;
  msg_business_type_name?: string;
  staff_id?: number;
  staff_name?: string;
  content?: NotifyContent;
}

export interface NotifyMsgListData {
  total: number;
  list: Array<NotifyMsg>;
  total_unread_num: number;
}

export interface NotifyMsgListReq {
  /** 业务区分 */
  msg_business_type?: number;
  page_size?: number;
  page_num?: number;
}

export interface NotifyMsgListResp {
  code: number;
  message: string;
  data: NotifyMsgListData;
}

export interface UpdateNotifyMsgStatusReq {
  /** 消息ID */
  msg_id: number;
  /** 消息状态 */
  status: NotifyMsgStatus;
}

export interface UpdateNotifyMsgStatusResp {
  code: number;
  message: string;
}
/* eslint-enable */
