// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface Data {
  url: string;
}

export interface GetPageUrlRes {
  code?: number;
  data?: Data;
  message?: string;
  status?: string;
  statusCode?: number;
  success?: boolean;
}

export interface QPageReq {
  /** 平台来源，建议添加，方便统计使用方 */
  clickAuditFrom?: string;
  /** 支持直接重定向到对应的审核页面 */
  redirect?: boolean;
  /** 【必须】有业务含义的唯一id，如计划，创意，素材, 召回 recallId */
  objectId?: string;
  /** 指定唯一的日志id下的objectId对应的信息来还原审核页面 */
  auditLogId?: string;
  /** 不含业务含义的唯一id，如通用召回链路的派单id，巡检链路的派单id; 当这里不为空时，且没有输入队列（objectCategory or queueKey），则查询日志时，优先查询通用召回记录 */
  taskId?: string;
  /** 队列的objectCategory， 没有输入则会从日志检索 */
  objectCategory?: string;
  /** 队列的objectType，没有输入则会从队列中心检索 */
  objectType?: string;
  /** 队列, 没有输入则会通过objectCategory+objectType 来生成（objectCategory+objectType 高优用自定义输入，低优服务自动获取，详见相关部分描述） */
  queueKey?: string;
  /** 指定 objectId 的目标用户的审出记录对应的页面 */
  staffId?: string;
  /** objectId未审出的情况下，且没有自定义队列objectCategory or queueKey）入参时，是否需要查询对应的审核链接，默认true，只查询审出任务场景建议关闭，速度更快 */
  retrieveUnAudit?: boolean;
}
/* eslint-enable */
