// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface GetQPermissionRes {
  code: number;
  message: string;
  data: boolean;
  status?: string;
}

export interface QPermissionReq {
  category?: string;
  points?: string;
}
/* eslint-enable */
