// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface ExportSheetReq {
  records?: Array<Record<string, string>>;
  rawSheetData?: Array<Record<string, string>>;
  defaultHeader?: Array<Header>;
  sheetName: string;
  lark?: boolean;
  sortCols?: Array<string>;
  folder?: string;
  fileName?: string;
  typeMap?: Record<string, string>;
}

export interface ExportSheetResponse {
  code: number;
  message: string;
  data?: SheetResponseData;
  status: string;
  statusCode: number;
  success: boolean;
}

export interface ExportSheetV2Options {
  sortCols?: Array<string>;
  typeMap?: Record<string, string>;
  defaultHeader?: Array<Header>;
  parentFolder?: string;
  fileName?: string;
}

export interface ExportSheetV2Req {
  lark: boolean;
  sheetName: string;
  records: Array<Record<string, string>>;
  rawSheetData?: Array<Record<string, string>>;
  options?: ExportSheetV2Options;
}

export interface Header {
  key: string;
  title: string;
}

export interface SheetResponseData {
  xlsxData?: XlsxFileResponse;
  urlData?: UrlResponse;
}

export interface UrlResponse {
  title?: string;
  folder_token?: string;
  url?: string;
  spreadsheet_token?: string;
  without_mount?: boolean;
}

export interface XlsxFileResponse {
  data: Blob;
  fileName: string;
  contentType: string;
}
/* eslint-enable */
