// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface ModifyRequest {
  service_name?: string;
  region?: string;
  confspace?: string;
  key?: string;
  value?: string;
  from_version?: number;
  env?: string;
  note?: string;
  app_name?: string;
  operator?: string;
  token?: string;
  service_id?: number;
  config_id?: number;
}

export interface ModifyTCCData {
  error_code?: number;
  data?: Record<string, string>;
}

export interface ModifyTCCResp {
  code: number;
  message: string;
  data?: ModifyTCCData;
  status?: string;
  statusCode?: number;
  success?: boolean;
}
/* eslint-enable */
