// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface Base64ImageUploadRequest {
  accessType?: string;
  fileKey?: string;
  bizType?: string;
  source: string;
}

export interface CallbackRequest {
  uris?: Array<string>;
  type: string;
  biz_type?: string;
  access_type?: string;
}

export interface CallbackResp {
  statusCode?: number;
  status?: string;
  code?: number;
  message?: string;
  msg?: string;
  success?: boolean;
}

export interface EmptyRequest {}

export interface FileImageUploadRequest {
  bizType?: string;
}

export interface FileUploadData {
  url?: string;
}

export interface FileUploadResp {
  statusCode?: number;
  status?: string;
  code?: number;
  message?: string;
  msg?: string;
  success?: boolean;
  data?: FileUploadData;
}

export interface ImageUploadData {
  url?: string;
  size?: number;
}

export interface ImageUploadRequest {
  accessType?: string;
  fileKey?: string;
  bizType?: string;
  fileData?: Blob;
}

export interface ImageUploadResp {
  statusCode?: number;
  status?: string;
  code?: number;
  message?: string;
  msg?: string;
  success?: boolean;
  data?: ImageUploadData;
}

export interface TokenData {
  AccessKeyId: string;
  SecretAccessKey: string;
  CurrentTime?: string;
  ExpiredTime?: string;
  SessionToken?: string;
}

export interface TokenResp {
  statusCode?: number;
  status?: string;
  code?: number;
  data?: TokenData;
  message?: string;
  msg?: string;
  success?: boolean;
}

export interface VideoTokenRequest {
  space?: string;
}
/* eslint-enable */
